In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
arr ** arr

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489], dtype=int32)

In [11]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [12]:
np.max(arr)

9

In [13]:
arr.max()

9

In [16]:
arr = arr+0.001
np.log(arr)

array([-6.90775528e+00,  9.99500333e-04,  6.93647056e-01,  1.09894557e+00,
        1.38654433e+00,  1.60963789e+00,  1.79192612e+00,  1.94605300e+00,
        2.07956653e+00,  2.19733568e+00])