In [1]:
import numpy as np

In [2]:
# Creating NumPy Array

In [3]:
my_list = [1,2,3]

In [5]:
type(np.array(my_list))

numpy.ndarray

In [6]:
#numpy matrix
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [9]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [28]:
#zero matrix
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
#ones matrix
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0, 10, 51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [21]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
#uniform distribution
np.random.rand(5,4)

array([[0.62138144, 0.92726151, 0.03857551, 0.90938656],
       [0.65636832, 0.64949256, 0.07658312, 0.41673449],
       [0.1802722 , 0.67119291, 0.06675007, 0.10054682],
       [0.81217992, 0.84323311, 0.48106979, 0.34918416],
       [0.27593095, 0.90832338, 0.46260411, 0.84534025]])

In [27]:
#gaussian/normal distribution
np.random.randn(5, 4)

array([[ 0.89272234, -1.34501343, -0.13968987,  0.32692904],
       [-1.71997114,  1.30298507,  3.34676715,  0.99964981],
       [ 1.46806578, -0.50456009,  1.38550826,  2.2765153 ],
       [ 0.32117138, -1.21044729, -0.28870908,  1.26775968],
       [ 0.27365912, -0.34589876,  0.0957286 ,  0.15415548]])

In [31]:
#random integer
np.random.randint(1,100, 10)

array([46, 46, 16, 27, 86,  7, 92, 42, 16, 99])

In [33]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [34]:
ranarr

array([21,  3, 28, 39, 22, 14,  4, 45,  8, 30])

In [35]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr.shape

(25,)

In [38]:
arr.reshape(5, 5).shape

(5, 5)

In [39]:
arr.dtype

dtype('int32')

In [40]:
arr.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [41]:
ranarr.max()

45

In [42]:
ranarr.argmax()

7

In [43]:
ranarr.min()

3

In [44]:
ranarr.argmin()

1