In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# Broadcasting an array
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
arr[] = 100

SyntaxError: invalid syntax (<ipython-input-8-a452b711de4d>, line 1)

In [9]:
arr[:]

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)

In [13]:
slice = arr[0:5]
slice

array([0, 1, 2, 3, 4])

In [15]:
# Pointer is copied
slice[:] = -29
slice

array([-29, -29, -29, -29, -29])

In [16]:
arr

array([-29, -29, -29, -29, -29,   5,   6,   7,   8,   9,  10])

In [17]:
# Makes an actual copy
arr_copy = arr.copy()
arr_copy

array([-29, -29, -29, -29, -29,   5,   6,   7,   8,   9,  10])

In [18]:
arr_copy[:] = 10
arr_copy

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [19]:
arr

array([-29, -29, -29, -29, -29,   5,   6,   7,   8,   9,  10])

In [20]:
# mat[row, col]
# mat[row][col]

In [21]:
mat = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
mat[0]

array([ 5, 10, 15])

In [23]:
mat[2]

array([35, 40, 45])

In [24]:
mat[1,1]

25

In [25]:
mat[1][1]

25

In [26]:
mat[0][2]

15

In [28]:
# Matrix slicing
mat[:2, 1:]

array([[10, 15],
       [25, 30]])

In [29]:
mat[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [30]:
mat[2][:2]

array([35, 40])

In [31]:
mat[-1]

array([35, 40, 45])

In [32]:
mat[-3]

array([ 5, 10, 15])

In [33]:
# CONDITIONAL SELECTION
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
bool_arr = arr > 4

In [37]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [39]:
arr[arr >= 4]

array([ 4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[arr > 3 and arr < 9]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()